[package]
name = "app"
version = "0.1.0"
authors = ["alephium devs"]
edition = "2021"

[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" } 
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git" } 
utils= { path = "../utils" }

[features]
default = ["device"]
debug = ["nanos_sdk/speculos", "nanos_ui/speculos"]
device = []

[profile.release]
opt-level = 'z'
lto = true

[package.metadata.nanos]
name = "Alephium"
curve = ["secp256k1"]
flags = "0"
icon = "crab.gif"
icon_small = "crab_14x14.gif"
path = [""]
