[package]
name = "app"
version = "0.2.0"
authors = ["alephium devs"]
edition = "2021"

[dependencies]
ledger_device_sdk = "1.4.1"
ledger_secure_sdk_sys = "1.0.3"
utils= { path = "../utils" }

[features]
default = ["device"]
debug = ["ledger_device_sdk/speculos", "ledger_device_sdk/speculos"]
device = []

[profile.release]
opt-level = 'z'
lto = true

[package.metadata.nanos]
name = "Alephium"
curve = ["secp256k1"]
flags = "0"
icon = "alph.gif"
icon_small = "alph_14x14.gif"
path = ["m/44'/1234'"]
api_level = "1"
