[package]
name = "app"
version = "0.2.0"
authors = ["alephium devs"]
edition = "2021"

[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" } 
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git", rev = "6a7c4a3eb41ee0b09c8fd4dcc5be4f3a1f5d7b45" } 
utils= { path = "../utils" }

[features]
default = ["device"]
debug = ["nanos_sdk/speculos", "nanos_ui/speculos"]
device = []

[profile.release]
opt-level = 'z'
lto = true

[package.metadata.nanos]
name = "Alephium"
curve = ["secp256k1"]
flags = "0"
icon = "alph.gif"
icon_small = "alph_14x14.gif"
path = ["m/44'/1234'"]
