name: Unit Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  speculos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: make set-github-action
      - run: cd js && npm ci && npm test -- --forceExit
